### ISSUE TITLE
Not able to send mail from signup form using gmail account

### ISSUE THREAD

**Issue by anil7-rvce** [coolcsn/CsnUser#52]
Additional information:
**Zend\Mail\Protocol\Exception\RuntimeException**
File:
**C:\xampp\htdocs\CsnUser\vendor\zendframework\zendframework\library\Zend\Mail\Protocol\AbstractProtocol.php:209**
Message:
**A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.**
Stack trace:
#0 C:\xampp\htdocs\CsnUser\vendor\zendframework\zendframework\library\Zend\Mail\Protocol\Smtp.php(148): Zend\Mail\Protocol\AbstractProtocol->_connect('tcp://mail.goog...')
#1 C:\xampp\htdocs\CsnUser\vendor\zendframework\zendframework\library\Zend\Mail\Transport\Smtp.php(375): Zend\Mail\Protocol\Smtp->connect()
#2 C:\xampp\htdocs\CsnUser\vendor\zendframework\zendframework\library\Zend\Mail\Transport\Smtp.php(361): Zend\Mail\Transport\Smtp->connect()
#3 C:\xampp\htdocs\CsnUser\vendor\zendframework\zendframework\library\Zend\Mail\Transport\Smtp.php(372): Zend\Mail\Transport\Smtp->lazyLoadConnection()
#4 C:\xampp\htdocs\CsnUser\vendor\zendframework\zendframework\library\Zend\Mail\Transport\Smtp.php(229): Zend\Mail\Transport\Smtp->connect()
#5 C:\xampp\htdocs\CsnUser\vendor\coolcsn\csn-user\src\CsnUser\Controller\RegistrationController.php(507): Zend\Mail\Transport\Smtp->send(Object(Zend\Mail\Message))
#6 C:\xampp\htdocs\CsnUser\vendor\coolcsn\csn-user\src\CsnUser\Controller\RegistrationController.php(85): CsnUser\Controller\RegistrationController->sendEmail('anil@mendios.co...', 'Please, confirm...', 'Please, click t...')
#7 C:\xampp\htdocs\CsnUser\vendor\zendframework\zendframework\library\Zend\Mvc\Controller\AbstractActionController.php(82): CsnUser\Controller\RegistrationController->indexAction()
#8 [internal function]: Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
#9 C:\xampp\htdocs\CsnUser\vendor\zendframework\zendframework\library\Zend\EventManager\EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#10 C:\xampp\htdocs\CsnUser\vendor\zendframework\zendframework\library\Zend\EventManager\EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#11 C:\xampp\htdocs\CsnUser\vendor\zendframework\zendframework\library\Zend\Mvc\Controller\AbstractController.php(118): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#12 C:\xampp\htdocs\CsnUser\vendor\zendframework\zendframework\library\Zend\Mvc\DispatchListener.php(93): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
#13 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#14 C:\xampp\htdocs\CsnUser\vendor\zendframework\zendframework\library\Zend\EventManager\EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#15 C:\xampp\htdocs\CsnUser\vendor\zendframework\zendframework\library\Zend\EventManager\EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#16 C:\xampp\htdocs\CsnUser\vendor\zendframework\zendframework\library\Zend\Mvc\Application.php(314): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#17 C:\xampp\htdocs\CsnUser\public\index.php(17): Zend\Mvc\Application->run()
#18 {main}

I'm confused what's the problem is actually
Below I have given code of *mail.config.local.php* file
**return array(
	'mail' => array(
		'transport' => array(
			'options' => array(
				'host' => 'mail.google.com',
				//'host' => 'smtp.gmail.com',
				'connection_class'  => 'plain',
				'port' => '465',
				'connection_config' => array(
					'username' => 'emailaddress',
					'password' => 'mypassword',
					'ssl' => 'tls'
				),
			),  
		),
	),
);**

**Comment by ellipizle** [comment]
use this config
```php
     'host' => 'smtp.gmail.com',
     'port' => '587',
     'connection_class' => 'login',
     'connection_config' => array(
     'username' => 'example@gmail.com',
     'password' => 'elpmaxe',
     'ssl' => 'tls',
     ),
```

**Comment by anil7-rvce** [comment]
@Ellipizle 

Not working either!!!

**An error occurred**
5.7.14 Please log in via your web browser and 5.7.14 then try again. 5.7.14 Learn more at 5.7.14 https://support.google.com/mail/answer/78754 s13sm15295680pfk.26 - gsmtp

**Additional information:**
Zend\Mail\Protocol\Exception\RuntimeException
File:
C:\xampp\htdocs\CsnUser\vendor\zendframework\zendframework\library\Zend\Mail\Protocol\AbstractProtocol.php:327
**Message:
![1](https://cloud.githubusercontent.com/assets/25499770/23499648/f87178f6-ff52-11e6-9469-51ef4749d68d.PNG)
![2](https://cloud.githubusercontent.com/assets/25499770/23499682/158b9610-ff53-11e6-8ff3-82122d5974d5.PNG)

**
5.7.14 <https://accounts.google.com/signin/continue?sarp=1&scc=1&plt=AKgnsbu9
 5.7.14 DFbfWaAYoS4kx1wf-V272uiVwHYbzDTtbdDTI7Z1Zel56485gdUFYkaUoUVWWZazjngoYd
 5.7.14 hAbwmKeiQnAMI2yzZZKuBlbZIROUjDb70MkdfjKRH201TJgaP763PiSk1Hr-sfn2ZQ4GXH
 5.7.14 h-BKvK8sckXSso_7lT8r3476dzSk0Ccx84IPgCHObPv8xZDTZRcz0sWVZzQPWrAJDdZmNq
 5.7.14 zGmda7-KOPTCQiQw9k0CPTsdhprRo> Please log in via your web browser and
 5.7.14 then try again.
 5.7.14  Learn more at
 5.7.14  https://support.google.com/mail/answer/78754 s13sm15295680pfk.26 - gsmtp
